# SHA1:ddff3f126978358816fc9518b85c5efc1ff00444
#
# This file is autogenerated by pip-compile-multi
# To update, run:
#
#    pip-compile-multi
#
exceptiongroup==1.2.2
    # via pytest
iniconfig==2.0.0
    # via pytest
numpy==2.0.1
    # via
    #   -r basetest.in
    #   pandas
packaging==24.1
    # via pytest
pandas==2.2.2
    # via -r basetest.in
pluggy==1.5.0
    # via pytest
pytest==8.3.2
    # via -r basetest.in
python-dateutil==2.9.0.post0
    # via pandas
pytz==2024.1
    # via pandas
six==1.16.0
    # via python-dateutil
tomli==2.0.1
    # via pytest
tzdata==2024.1
    # via pandas
